### Get all menu items
GET http://localhost:8080/api/menu-item
Accept: application/json

### Get menu items by restaurant ID
GET http://localhost:8080/api/menu-item/restaurantId/3
Accept: application/json

### Get menu items by name
GET http://localhost:8080/api/menu-item/restaurantName/Tacos%20El%20Pastorcito
Accept: application/json

### Post a new menu item
POST http://localhost:8080/api/menu-item
Content-Type: application/json

{
  "name": "Pizzetta Margherita",
  "description": "A small, delicious pizza topped with fresh tomatoes, mozzarella cheese, and basil leaves.",
  "price": 9.99,
  "restaurantId": 6,
  "calories": 700
}

### Update an existing menu item
PUT http://localhost:8080/api/menu-item/id/18
Content-Type: application/json

{
  "name": "Pizzetta Margherita",
  "description": "A small, delicious pizza topped with fresh tomatoes, mozzarella cheese, and basil leaves.",
  "price": 29.99,
  "restaurantId": 6,
  "calories": 700
}

### Delete a menu item
DELETE http://localhost:8080/api/menu-item/id/4
Content-Type: application/json