### Get all restaurants
GET http://localhost:8080/api/restaurant
Accept: application/json

### Get a specific restaurant by ID
GET http://localhost:8080/api/restaurant/id/3

### Get a specific restaurant by name
GET http://localhost:8080/api/restaurant/name/Sushi%20Zen

### Get opens restaurants
GET http://localhost:8080/api/restaurant/open

### Get restaurants by rate
GET http://localhost:8080/api/restaurant/rate/4

### Get restaurants by food type
GET http://localhost:8080/api/restaurant/foodType/Italian

### Post a new restaurant
POST http://localhost:8080/api/restaurant
Content-Type: application/json

{
  "name": "Carlos' Pizzeria",
  "foodType": "Chinese",
  "address": "456 Elm St, Othertown",
  "openHour": "10:00",
  "closeHour": "23:00",
  "rate": 3,
  "userId": 7

}

### Get all restaurant by owner
GET http://localhost:8080/api/restaurant/ownerId/3
Content-Type: application/json

### Update an existing restaurant
PUT http://localhost:8080/api/restaurant/id/11
Content-Type: application/json

{
  "name": "Carlos' Pizzeria",
  "foodType": "Taiwanese",
  "address": "456 Elm St, Othertown",
  "openHour": "10:00",
  "closeHour": "23:00",
  "rate": 3,
  "userId": 7

}

### Delete a restaurant by ID
DELETE http://localhost:8080/api/restaurant/id/1
Content-Type: application/json

