spring:
  application:
    name: quickbite
  datasource:
    url: jdbc:postgresql://localhost:5432/quickbite
    username: postgres
    password: motudin2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 'create' for fresh DB, 'update' for development, 'validate' for production
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
app:
  page-size: 12